dependencies:
  - codecov
  - fastapi
  - geopandas
  - httpx
  - metpy
  # Modern
  - pandas>=3
  - pygrib
  - pyogrio
  - pyproj
  - pytest
  - pytest-cov
  # For httpx request mocking
  - pytest-httpx
  - pytest-runner
  - setuptools_scm
  - sqlalchemy
  # For logging
  - uvicorn
